apiVersion: v1
kind: Deployment
metadata:
 name: test-rc 
 labels: 
   app: myapp
   type: fe 
spec:
  template:
    metadata: 
      name: test
      labels:
            app: myappfe
            type: front-end
    spec:
      containers:
         - name: prabhu
           image: nginx
  replicas: 3
