apiVersion: v1
kind: ReplicationController
metadata:
 name: test-rc 
 labels: 
   app: myapp
   type: fe 
spec:
  template:
    metadata: 
      name: test
    spec:
      containers:
         - name: prabhu
           image: nginx
  replicas: 3
           
