apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: test-rc
 labels:
   app: myapp
   type: front-end
spec:
  template:
    metadata:
      name: test
      labels:
        app: kat
        type: front-end
    spec:
      containers:
         - name: prabhu
           image: nginx
  replicas: 3
  selector:
        matchLabels:
                type: front-end
