apiVersion: v1
kind: Service
metadata:
 name: test-rc-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: test-rc
    type: front-end
